name:                russian-towers
version:             0.1.0.0
github:              "githubuser/russian-towers"
license:             BSD3
author:              "Dmitry Barskov"
maintainer:          "dmitry.barskov64@gmail.com"
copyright:           "2020 Dmitry Barskov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/russian-towers#readme>

dependencies:
- base >= 4.7 && < 5
- MonadRandom
- aeson
- servant
- servant-server
- stm
- mtl

library:
  source-dirs: src

executables:
  russian-towers-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - russian-towers

tests:
  russian-towers-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - russian-towers
